<a href="https://colab.research.google.com/github/mastgm0817/DataAnalysis/blob/main/mastgm0817/Ch05/ch05_02_%EB%B0%B0%EC%97%B4%EC%9D%98_%EC%83%9D%EC%84%B1%EA%B3%BC_%EB%B3%80%ED%98%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 배열의 생성과 변형

## Numpy의 자료형
* Numpy의 배열 즉, `ndarray` 클래스는 원소가 모두 같은 자료형이어야 함
* `array` 명령으로 배열을 만들 때 자료형을 명시적으로 적용하려면 `dtype` 인수를 사용
* 만약 `dtype` 인수가 없으면 주어진 데이터를 저장할 수 있는 자료형을 스스로 유추
* 만들어진 배열의 자료형을 알아내려면 `dtype` 속성을 사용 


In [ ]:
import numpy as np

x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [ ]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

* `dtype` 인수
    * dtype 접두사로 시작하는 문자열
    * 접두사 뒤 오는 숫자 = 바이트 수 혹은 글자 수
    * 숫자 생략 시 운영체제에 따라 알맞은 크기 지정

|dtype 접두사|설명|사용 예|
|-|-|-|
|`b`|불리언|`b` (참 혹은 거짓)|
|`i`|정수|`i8` (64비트)|
|`u`|부호 없는 정수|`u8` (64비트)|
|`f`|부동소수점|`f8` (64비트)|
|`c`|복소 부동소수점|`c16` (128비트)|
|`O`|객체|`0` (객체에 대한 포인터)|
|`S`|바이트 문자열|`S24` (24 글자)|
|`U`|유니코드 문자열|`U24` (24 유니코드 글자)|

In [ ]:
x = np.array([1, 2, 3], dtype='f') # float -> 32
# x = np.array([1, 2, 3], dtype=float) # float -> 64
x.dtype

dtype('float32')

In [ ]:
x[0] + x[1]

3.0

In [ ]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [ ]:
x[0] + x[1]

'12'

## Inf와 NaN
* Numpy에서는 무한대를 표현하기 위한 `np.inf`(infinity)와 정의할 수 없는 숫자를 나타내는 `np.nan(not a number)`을 사용


In [2]:
import numpy as np
# 1을 0으로 나누려고 할 때, 0을 0으로 나누려고 시도...
np.array([0,1,-1,0]) / np.array([1,0,0,0]) # inf:무한대, -inf:-무한대, nan:not a number

<ipython-input-2-d3a2e2450a41>:3: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])
<ipython-input-2-d3a2e2450a41>:3: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [3]:
# 0에 대한 로그 값을 계산
np.log(0) 

<ipython-input-3-cc64fe1345a2>:2: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

## 배열 생성
* `zeros`, `ones`
* `zeros_like`, `ones_like`
* `empty`
* `arange`
* `linspace`, `logspace`

### zeros : 크기가 정해져 있고 모든 값이 0인 배열 생성

In [5]:
# 정수를 넣으면 해당 크기의 0으로 채워진 1차원 배열 생성
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [17]:
# 튜플을 넣으면 해당 크기의 0으로 채워진 다차원 배열 생성
b = np.zeros((2,3)) # 행이 2고 열이 3인 상태로 0을 채워서 만듦듦
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# dtype 인수 명시 시 해당 자료형 원소 타입 부여
a = np.zeros((5,2), dtype="i")
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [9]:
# 문자열 배열도 가능하지만, 모든 원소의 문자열 크기가 같아야 함
# 만약 더 큰 크기의 문자열을 할당하면 잘림
a = np.zeros(5,dtype="U4") #0으로 채워야하는데 문자열로 바꾸면 0은 ""로 변환됨
a

array(['', '', '', '', ''], dtype='<U4')

In [11]:
a[0] ="abc"
a[1] ="abcd"
a[2] = ("abcd" + "e").upper() #ABCDE
a # 5번째 글자부터는 삭제됨 U4라라

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

### ones : 1로 초기화된 배열을 생성 

In [14]:
e = np.ones((2,3,4,5), dtype=int)
e

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]])

### ones_like, zeros_like : 다른 배열과 같은 크기의 배열을 생성

In [19]:
f = np.ones_like(b, dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [20]:
f = np.zeros_like(b, dtype='f')
f

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

# ones 와 zeros가 필요한 이유는 ones는 행렬끼리 곱할때, zeros는 행렬끼리 더할때

# bool도 고려함함

### empty : 값 초기화 없이 배열을 생성 (시간 절약)
* 기존 메모리에 저장되어 있던 값이 있음
* 배열의 원소 값을 미리 알 수 없음

In [21]:
g = np.empty((4,3))
g

array([[3.0701437e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

### arange : 특정 규칙에 따라 증가하는 수열을 만듦 (like `range`)

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(3,20,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

### linspace, logspace : 선형 구간 또는 로그 구간을 지정한 구간의 수만큼 분할

In [25]:
# linspace (liner space 선형(평탄하게)으로 증가/감소한다는 의미)
np.linspace(0,100,5) # 0부터 100까지 인데 5개의 조각으로 나누겠다는 의미, range랑 헷갈리지 말것


array([  0.,  25.,  50.,  75., 100.])

In [26]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## 전치 연산 (transpose)
* 2차원 배열에서 행과 열을 바꾸는 작업
* 배열의 `T` **속성**

In [33]:
a = np.arange(1,7).reshape(2,3)
a.ndim, a.shape

(2, (2, 3))

In [32]:
a2 = a.T
a2.ndim, a2.shape

(2, (3, 2))

## 배열의 크기 변형 (`reshape`)

In [35]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
# 사용하는 원소의 갯수가 정해져 있기 때문에
# reshape 명령의 형태 튜플 원소 중 하나는 -1으로 대체 가능
# -1을 넣으면 해당 숫자는 다른 값을 통해 계산되어서 사용
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [39]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

## 배열 평탄화 (`flatten`, `ravel`)
* 다차원 배열을 1차원으로 변환

In [40]:
a.reshape(len(a))
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 같은 배열에 대해 차원만 1차원 증가 (`newaxis`)

#### 흑백사진을 하나의 색깔로 변형할때때

In [47]:
x = np.arange(5)
print(x, x.ndim, x.shape)
# print(x)
x2 = x[:, np.newaxis]
print(x2, x2.ndim, x2.shape)
x3 = x[np.newaxis, :]
print(x3, x3.ndim, x3.shape)


[0 1 2 3 4] 1 (5,)
[[0]
 [1]
 [2]
 [3]
 [4]] 2 (5, 1)
[[0 1 2 3 4]] 2 (1, 5)


## 배열 연결
* 행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하여 더 큰 배열을 생성 (concatenate)
    * `hstack`
    * `vstack`
    * `dstack`
    * `stack`
    * `r_`
    * `c_`
    * `tile`

### `concatenate`

array([1, 2, 3, 4, 5, 6])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### `hstack`
* 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 만듦
* 연결할 배열은 하나의 리스트에 담아야 함

array([[1., 1., 1.],
       [1., 1., 1.]])

array([[0., 0.],
       [0., 0.]])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

### `vstack`
* 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열을 만듦
* 연결할 배열은 하나의 리스트에 담아야 함

array([[1., 1., 1.],
       [1., 1., 1.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### `dstack`
* 제3의 축 즉, 행이나 열이 아닌 깊이(depth) 방향으로 배열을 합침
* 가장 안쪽의 원소의 차원이 증가, 즉 가장 내부의 숫자 원소가 배열이 됨

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

(3, 4, 2)

### `stack`
* `dstack`의 기능을 확장한 것으로 `dstack`처럼 마지막 차원으로 연결하는 것이 아니라 사용자가 지정한 차원(축으로) 배열을 연결
* axis 인수(디폴트 0)를 사용하여 연결후의 회전 방향을 정함
* 디폴트 인수값은 0이고 가장 앞쪽에 차원이 생성. 즉, 배열 두 개가 겹치게 되므로 연결하고자 하는 배열들의 크기가 모두 같아야 함

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

(2, 3, 4)

* `axis` 인수가 1이면 두번째 차원으로 새로운 차원이 삽입

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

(3, 2, 4)

### `r_`
* `hstack` 명령과 비슷하게 배열을 좌우로 연결
* 다만 메서드임에도 불구하고 소괄호(parenthesis, `()`)를 사용하지 않고 인덱싱과 같이 대괄호(bracket, `[]`)를 사용
* 이런 특수 메서드를 인덱서(indexer)라고 함

array([1, 2, 3, 4, 5, 6])

### `c_`
* 배열의 차원을 증가시킨 후 좌우로 연결

array([[1, 4],
       [2, 5],
       [3, 6]])

### `tile`
* 동일한 배열을 반복하여 연결

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

## 💡 연습문제 4
```
array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])
```

array([0., 0., 0.], dtype=float32)

array([1., 1.], dtype=float32)

array([0., 0., 0., 1., 1.], dtype=float32)

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]], dtype=float32)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.,
       120., 130., 140., 150.], dtype=float32)

array([[ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]], dtype=float32)

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]], dtype=float32)

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]], dtype=float32)

## 배열 분할

[array([1, 2]), array([3, 4]), array([5, 6])]

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]), array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]