<a href="https://colab.research.google.com/github/CHOISEONGGU/DataAnalysis_ChoiSG/blob/main/CHOISEONGGU/%EA%B3%B5%EB%B6%80%EC%9E%90%EB%A3%8C/ch05_04_%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84%2B%EB%82%9C%EC%88%98%EB%B0%9C%EC%83%9D%EA%B3%BC%2B%EC%B9%B4%EC%9A%B4%ED%8C%85_ChoiSG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기술 통계

## 기술 통계(descriptive statistics)
> 데이터 집합에 대해 통계를 계산
* 데이터의 개수(count)
* 평균(mean, average)
* 분산(variance)
* 표준 편차(standard deviation)
* 최댓값(maximum)
* 최솟값(minimum)
* 중앙값(median)
* 사분위수(quartile)

In [1]:
import numpy as np

In [2]:
x = np.array([
    18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
    2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13
])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

## 데이터의 개수

In [6]:
len(x)

26

## 표본 평균
* 우리가 일반적으로 아는 평균
* 통계용어로는 표본 평균(sample average, sample mean)
<br>
$
\bar{x} = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{x_i}
$
(𝑁은 데이터의 개수)

In [7]:
np.mean(x), x.mean()

(4.8076923076923075, 4.8076923076923075)

## 표본 분산
* 표본 분산(sample variance) : 데이터와 표본 평균간의 거리의 제곱의 평균
* 표본 분산이 작으면 데이터가 모여있는 것이고 크면 흩어져 있는 것
<br>
$
s^2 = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{(x_i-\bar{x})^2}
$

In [8]:
np.var(x)

115.23224852071006

## 표본 표준편차
* 표본 표준편차(sample standard variance) : 표본 분산의 양의 제곱근 값 
<br>
$
s = \sqrt{s^2}
$

In [9]:
np.std(x)   # std : standard variance

10.734628476137871

## 최댓값과 최솟값

In [ ]:
# 최댓값 (maximum) / 최솟값 (minimum)


(23, -24)

## 중앙값
* 중앙값(median) : 데이터를 크기대로 정렬하였을 때 가장 가운데에 있는 수
* 만약 데이터의 수가 짝수이면 가장 가운데에 있는 두 수의 평균을 사용


5.0

## 사분위수
* 사분위수(quartile) : 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수
* 각각 1사분위수, 2사분위수, 3사분위수라고 함
* 1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%
* 따라서 2사분위수는 중앙값과 같음
* 때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 함
* 1사분위수는 25% 백분위수와 같음


In [11]:
np.percentile(x, 0)   # 최솟값

-24.0

In [10]:
np.percentile(x, 25)   # 25% 백분위수, 1사분위수

0.0

In [ ]:
np.percentile(x, 50)   # 50% 백분위수, 2사분위수, 중앙값

5.0

In [ ]:
np.percentile(x, 75)   # 75% 백분위수, 3사분위수

10.0

In [12]:
np.percentile(x, 100)   # 100% 백분위수, 최댓값

23.0

# 난수 발생과 카운팅

## 시드 설정
* 컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아님
* 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성. 이런 시작 숫자를 시드(seed)라고 함
* 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 됨. 따라서 시드값은 한 번만 정해주면 됨.
* 시드는 보통 현재 시각 등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있음 * 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있음
* 고정된 결과를 얻기 위해서 실습엔 시드를 설정

In [13]:
np.random.seed(0)   # 시드값 고정 : project할때 seed 고정해놓고 보통 진행한다.

### `rand` : 0과 1 사이의 난수를 발생

In [20]:
np.random.rand(5) # rand(n) : n개의 길이를 가지는 배열에 각각 0-1 사이의 난수를 채워줌

array([0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ])

In [21]:
np.random.rand(10)

array([0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
       0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077])

## 데이터의 순서 변경

### `shuffle`
* 데이터의 순서를 변경
* 자체 변환(in-place) 함수 (원본에 영향)

In [22]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.random.shuffle(x)
x

array([0, 4, 2, 6, 3, 7, 9, 8, 1, 5])

## 데이터 샘플링
* 표본선택 혹은 샘플링(sampling) : 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것

### `choice` : 샘플링에 사용
```
numpy.random.choice(a, size=None, replace=True, p=None)
```
* a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
* size : 정수. 샘플 숫자
* replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능 (복원/비복원 추출)
* p : 배열. 각 데이터가 선택될 수 있는 확률

In [38]:
np.random.choice(5, 5, replace=False)   # 5개 중에 5개를 선택 -> 비복원 -> shuffle
# replace -> True : 복원추출 / False : 비복원추출

array([1, 2, 4, 0, 3])

In [40]:
np.random.choice(5, 3, replace=False)   # 5개 중에 3개를 선택 -> 비복원

array([4, 2, 0])

In [41]:
# np.random.choice(5, 10, replace=True) # replace의 default => True 복원 추출
np.random.choice(5, 10)

array([4, 3, 3, 1, 0, 0, 1, 2, 0, 3])

In [46]:
# [ 0, 1, 2, 3, 4 ]
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])   # p(percentage) 나올 확률

array([2, 3, 3, 3, 3, 3, 3, 3, 0, 3])

## 난수 생성
* `rand` : 0부터 1 사이의 균일 분포
* `randn` : 표준 정규 분포
* `randint` : 균일 분포의 정수 난수

### `rand` : 0부터 1 사이에서 균일한 확률 분포로 실수 난수를 생성
* 숫자 인수는 생성할 난수의 크기
* 여러 개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

In [48]:
np.random.rand(10)

array([0.26726254, 0.67909062, 0.86428144, 0.75084425, 0.96448977,
       0.55424244, 0.2123905 , 0.22244322, 0.21874937, 0.56957353])

In [50]:
np.random.rand(3, 5)

array([[0.45210904, 0.97023668, 0.68054469, 0.08529557, 0.05641833],
       [0.4878377 , 0.88100456, 0.97640439, 0.61765792, 0.54249878],
       [0.85461358, 0.74383455, 0.47859633, 0.67708157, 0.60704506]])

### `randn` : 기댓값이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성

In [51]:
np.random.randn(10)

array([-0.25712774,  1.80981769,  0.8923485 , -0.09657613, -0.37715702,
       -0.50529774, -1.36267113,  1.13312703, -0.70068976, -1.7683479 ])

In [52]:
np.random.randn(3, 5)

array([[ 0.34041728,  0.72924169, -1.08835382, -2.87777873, -0.66147769],
       [ 0.70592839, -0.35859784,  0.73198245, -0.03636653,  0.58891422],
       [-0.77963481,  0.47633669,  0.83388012,  1.31379269, -0.6017086 ]])

### `randint`
```
numpy.random.randint(low, high=None, size=None)
```
만약 `high`를 입력하지 않으면 0과 `low`사이의 숫자, `high`를 입력하면 `low`와 `high`는 사이의 숫자를 출력. `size`는 난수의 숫자

In [53]:
np.random.randint(10, size=10)

array([4, 7, 4, 1, 3, 3, 9, 2, 5, 2])

In [56]:
np.random.randint(10,20,size=10)

array([13, 15, 17, 12, 17, 11, 16, 15, 10, 10])

array([[18, 10, 14, 19, 16],
       [15, 17, 18, 18, 19],
       [12, 18, 16, 16, 19]])

## 💡 연습문제 7
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 작성하라
2. 주사위를 100번 던져서 나오는 숫자의 평균
3. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [58]:
# 1.
np.random.choice([0,1], size=10, replace=True)

array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1])

In [64]:
# 2.
np.random.randint(1, 7, 100).mean()
np.random.choice(range(1, 7), replace=True).mean()

3.0

In [66]:
# 3.
a = np.random.randn(250) / 100  # 일간 수익률의 표준정규분포를 따르는 (0.1%) 수익률 분포

In [67]:
init = 10000
stock = np.empty(250)
for i, v in enumerate(a):
    init *= (1 + v)
    stock[i] = init
stock

array([ 9853.78296827,  9837.59769215,  9902.19496672,  9822.85847737,
        9741.56594087,  9685.56859062,  9683.55868167,  9572.30529042,
        9739.8580282 ,  9855.41348797,  9809.07853333,  9883.61023831,
        9855.64017985,  9790.98775388,  9912.60440272,  9767.0322103 ,
        9849.57018156,  9792.02993112,  9740.13194055,  9885.02709878,
        9826.87795067,  9689.27592207,  9985.50851258, 10018.01534006,
       10056.59769663, 10091.19657263,  9979.25341361, 10013.38819962,
        9955.62225248, 10068.3936895 , 10118.65170814, 10205.68850329,
       10201.32625291, 10193.6571869 , 10176.98271163, 10113.17507478,
       10279.68908892, 10268.04472567, 10405.47717005, 10441.45836961,
       10500.62352859, 10315.8306975 , 10186.2670329 , 10288.06124863,
       10292.19377744, 10344.52690569, 10368.87106038, 10280.26855203,
       10337.50663369, 10219.16217891, 10213.80133875, 10270.45190797,
       10252.07627357, 10231.21223657, 10271.79869859, 10379.14752103,
      

## 정수 데이터 카운팅
* 만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석

### `unique`
* unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
* return_counts 인수를 True 로 설정하면 각 값을 가진 데이터 갯수도 출력


In [69]:
# 고유한 값들을 다 분해해서 해석해준다
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [72]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [73]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [74]:
count

array([2, 2, 1])

In [75]:
dict(zip(*np.unique(a, return_counts=True)))

{'a': 2, 'b': 2, 'c': 1}

### `bincount`
* `unique` 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않음
* 따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 `bincount` 함수에 `minlength` 인수를 설정하여 쓰는 것이 더 편리
* `bincount` 함수는 0 부터 `minlength` - 1 까지의 숫자에 대해 각각 카운트
* 데이터가 없을 경우에는 카운트 값이 0이 됨

In [77]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0])

In [78]:
np.bincount([0, 0, 0, 1, 1, 2, 2, 2, 3, 4, 5, 6, 6, 6, 6], minlength=6)

array([3, 2, 3, 1, 1, 1, 4])