<a href="https://colab.research.google.com/github/Yeaaaaaaah/DataAnalysis/blob/main/Yeaaaaaaah/ch05_04_%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84%2B%EB%82%9C%EC%88%98%EB%B0%9C%EC%83%9D%EA%B3%BC%2B%EC%B9%B4%EC%9A%B4%ED%8C%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기술 통계

## 기술 통계(descriptive statistics)
> 데이터 집합에 대해 통계를 계산
* 데이터의 개수(count)
* 평균(mean, average)
* 분산(variance)
* 표준 편차(standard deviation)
* 최댓값(maximum)
* 최솟값(minimum)
* 중앙값(median)
* 사분위수(quartile)

In [1]:
import numpy as np

In [2]:
x = np.array([
    18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13
])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

## 데이터의 개수

In [3]:
len(x)

26

## 표본 평균
* 우리가 일반적으로 아는 평균
* 통계용어로는 표본 평균(sample average, sample mean)
<br>
$
\bar{x} = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{x_i}
$
(𝑁은 데이터의 개수)

In [4]:
np.mean(x), x.mean()

(4.8076923076923075, 4.8076923076923075)

## 표본 분산
* 표본 분산(sample variance) : 데이터와 표본 평균간의 거리의 제곱의 평균
* 표본 분산이 작으면 데이터가 모여있는 것이고 크면 흩어져 있는 것
<br>
$
s^2 = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{(x_i-\bar{x})^2}
$

In [5]:
np.var(x)

115.23224852071006

## 표본 표준편차
* 표본 표준편차(sample standard variance) : 표본 분산의 양의 제곱근 값 
<br>
$
s = \sqrt{s^2}
$

In [6]:
np.std(x)

10.734628476137871

## 최댓값과 최솟값

In [7]:
# 최댓값 (maximum) / 최솟값 (minimum)
np.max(x), np.min(x)

(23, -24)

## 중앙값
* 중앙값(median) : 데이터를 크기대로 정렬하였을 때 가장 가운데에 있는 수
* 만약 데이터의 수가 짝수이면 가장 가운데에 있는 두 수의 평균을 사용


In [8]:
np.median(x)

5.0

## 사분위수
* 사분위수(quartile) : 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수
* 각각 1사분위수, 2사분위수, 3사분위수라고 함
* 1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%
* 따라서 2사분위수는 중앙값과 같음
* 때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 함
* 1사분위수는 25% 백분위수와 같음


In [9]:
np.percentile(x, 0) # 최솟값

-24.0

In [10]:
np.percentile(x, 25) # 25%백분위수, 1사분위수

0.0

In [11]:
np.percentile(x, 50) # 50%백분위수, 2사분위수, 중앙값

5.0

In [12]:
np.percentile(x, 75) # 75%백분위수, 3사분위수,

10.0

In [13]:
np.percentile(x, 100) # 100%백분위수, 최대값,

23.0

# 난수 발생과 카운팅

## 시드 설정
* 컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아님
* 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성. 이런 시작 숫자를 시드(seed)라고 함
* 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 됨. 따라서 시드값은 한 번만 정해주면 됨.
* 시드는 보통 현재 시각 등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있음 * 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있음
* 고정된 결과를 얻기 위해서 실습엔 시드를 설정

In [22]:
np.random.seed(0) # 시드값 고정

### `rand` : 0과 1 사이의 난수를 발생

In [38]:
np.random.rand(5) # rand(n) n개의 길이를 가지는 배열에 각각 0~1 사이의 난수를 채워줍니다

array([0.26538949, 0.52324805, 0.09394051, 0.5759465 , 0.9292962 ])

In [39]:
np.random.rand(10)

array([0.31856895, 0.66741038, 0.13179786, 0.7163272 , 0.28940609,
       0.18319136, 0.58651293, 0.02010755, 0.82894003, 0.00469548])

## 데이터의 순서 변경

### `shuffle`
* 데이터의 순서를 변경
* 자체 변환(in-place) 함수 (원본에 영향)

In [40]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.random.shuffle(x)
x

array([7, 1, 5, 4, 0, 8, 9, 6, 3, 2])

## 데이터 샘플링
* 표본선택 혹은 샘플링(sampling) : 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것

### `choice` : 샘플링에 사용
```
numpy.random.choice(a, size=None, replace=True, p=None)
```
* a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
* size : 정수. 샘플 숫자
* replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능 (복원/비복원 추출)
* p : 배열. 각 데이터가 선택될 수 있는 확률

In [42]:
np.random.choice(5, 5, replace=False) # 5개 중에  5개를 선택 - > 비복원 -> shffle

array([1, 4, 3, 2, 0])

In [43]:
np.random.choice(5, 3, replace=False) #5개 중에 3개를 선택 ->  비복원

array([2, 1, 0])

In [46]:
# np.random.choice(5, 10, replace=True) #5개 중에 10개를 선택 -> 복원(기본적으로 True)
np.random.choice(5, 10)

array([1, 0, 4, 1, 3, 1, 0, 0, 4, 3])

In [52]:
# [0, 1, 2, 3, 4]
np.random.choice(5, 10, p =[0.1, 0, 0.3, 0.6, 0])

array([3, 3, 3, 3, 3, 3, 0, 3, 3, 2])

In [57]:
np.random.choice([1, 5, 10, 20, 100], 10, p =[0.7, 0.2, 0.05, 0.03, 0.02])

array([ 1,  1,  5,  1,  5,  1, 20,  1,  5,  1])

## 난수 생성
* `rand` : 0부터 1 사이의 균일 분포
* `randn` : 표준 정규 분포
* `randint` : 균일 분포의 정수 난수

### `rand` : 0부터 1 사이에서 균일한 확률 분포로 실수 난수를 생성
* 숫자 인수는 생성할 난수의 크기
* 여러 개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

In [60]:
np.random.rand(10)

array([0.4631502 , 0.84042853, 0.20486576, 0.16495887, 0.12483306,
       0.72208066, 0.03045296, 0.74699424, 0.09259617, 0.21745049])

In [61]:
np.random.rand(3, 5)

array([[0.74925442, 0.73169376, 0.04561464, 0.20915703, 0.28691504],
       [0.67726331, 0.06303829, 0.55564924, 0.00924007, 0.8330381 ],
       [0.98432943, 0.70349478, 0.1816312 , 0.51239346, 0.58044714]])

### `randn` : 기댓값이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성

In [62]:
np.random.randn(10)

array([ 0.48565189,  1.31152655, -0.23564945, -1.48017978, -0.02148475,
        1.05279068, -0.11740222,  1.82850826, -0.01667713,  1.87011107])

In [63]:
np.random.randn(3,5)

array([[-0.38030715,  0.42869794,  0.36189589,  0.46756761, -1.5180287 ],
       [-1.89304483, -0.78508653, -1.60529407,  1.43184023, -1.94219012],
       [ 1.13995339, -0.61716593, -1.77555859, -1.11820547, -1.60638701]])

### `randint`
```
numpy.random.randint(low, high=None, size=None)
```
만약 `high`를 입력하지 않으면 0과 `low`사이의 숫자, `high`를 입력하면 `low`와 `high`는 사이의 숫자를 출력. `size`는 난수의 숫자

In [83]:
np.random.randint(10, size = 5)

array([2, 8, 3, 0, 8])

In [81]:
np.random.randint(10, 21, size = 5)

array([16, 15, 19, 16, 15])

In [82]:
np.random.randint(10, 21, size = (3, 5))

array([[12, 17, 11, 19, 12],
       [12, 15, 16, 14, 12],
       [12, 11, 10, 19, 10]])

## 💡 연습문제 7
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 작성하라
2. 주사위를 100번 던져서 나오는 숫자의 평균
3. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [84]:
# 1.
np.random.choice([0,1], size=10, replace=True)

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0])

In [86]:
# 2.
# np.random.randint(1,7,100).mean()
np.random.choice(range(1,7), 100, replace = True).mean()

3.67

In [93]:
# 3.
a = np.random.randn(250) / 100 # 일간 수익률의 표준정규분포를 따르는 (0,1%) 수익률 분포
a

array([-4.26539773e-03,  9.08989438e-03,  1.47077291e-02, -1.00026975e-03,
       -4.15398075e-03, -2.02364760e-02,  7.84861147e-03, -6.21958642e-03,
        2.18945674e-02,  1.20229415e-02,  1.60613474e-02, -5.91632578e-03,
       -1.09107262e-02, -7.88976228e-03, -7.49195393e-03,  2.89323479e-03,
       -1.41971239e-04, -9.01044169e-03,  9.07474996e-03, -3.34321250e-03,
       -3.87453984e-03,  1.03955858e-07,  2.39405857e-03,  1.97096025e-03,
        5.91523141e-03, -8.04933727e-03, -1.10277324e-02, -7.62297844e-03,
        2.61313895e-03, -7.53841428e-03, -5.59614293e-03, -1.05585180e-02,
        3.66767864e-03,  1.80190374e-02, -2.03254007e-02, -7.22672405e-03,
       -7.20780931e-03,  4.95452879e-03, -2.90807701e-03, -1.03379078e-02,
        1.78548921e-03, -1.47532499e-02, -1.25129555e-02, -2.36760877e-02,
       -6.71237437e-03, -1.18691754e-02, -1.43758658e-02,  4.05150606e-03,
        7.62452611e-03,  7.83988566e-03, -1.07868102e-02, -8.39663135e-03,
        8.04505098e-03, -

In [94]:
init = 10000
stock = np.empty(250)
for i,v in enumerate(a):
  init *= (1 + v)
  stock[i] = init
stock

array([ 9957.34602272, 10047.85724636, 10195.63840869, 10185.44001998,
       10143.12989825,  9937.86869313, 10015.86716336,  9953.57261198,
       10171.50177842, 10293.79314902, 10459.12533669, 10397.24574387,
       10283.80424236, 10202.66747158, 10126.2295569 , 10155.52711651,
       10154.08532374, 10062.59253007, 10153.90804126, 10119.96136895,
       10080.75117548, 10080.75222343, 10104.88613468, 10124.80246355,
       10184.69301306, 10102.71298401,  9991.30296889,  9915.1394818 ,
        9941.04911896,  9866.10937233,  9810.89721412,  9707.30867968,
        9742.91196842,  9918.46986313,  9716.872989  ,  9646.65182929,
        9577.12060239,  9624.57072212,  9596.58172929,  9497.37315209,
        9514.33060942,  9373.96331262,  9256.66732678,  9037.50565904,
        8976.84253765,  8870.29481929,  8742.77665134,  8778.19806395,
        8845.12766431,  8914.47245382,  8818.31373176,  8744.26960221,
        8814.61769691,  8667.00281418,  8672.87838153,  8789.37066916,
      

## 정수 데이터 카운팅
* 만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석

### `unique`
* unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
* return_counts 인수를 True 로 설정하면 각 값을 가진 데이터 갯수도 출력


In [95]:
np.unique([11,11,2,2,34,24])

array([ 2, 11, 24, 34])

In [97]:
a = np.array(['a', 'b', 'c', 'a'])
np.unique(a,return_counts=True)

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 1, 1]))

In [98]:
a = np.array(['a', 'b', 'c', 'a'])
index, count = np.unique(a,return_counts=True)

In [100]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [102]:
count

array([2, 1, 1])

In [103]:
dict(zip(*np.unique(a, return_counts=True)))

{'a': 2, 'b': 1, 'c': 1}

### `bincount`
* `unique` 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않음
* 따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 `bincount` 함수에 `minlength` 인수를 설정하여 쓰는 것이 더 편리
* `bincount` 함수는 0 부터 `minlength` - 1 까지의 숫자에 대해 각각 카운트
* 데이터가 없을 경우에는 카운트 값이 0이 됨

In [105]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0])